### ISSUE TITLE
HTML Loading return an empty String

### ISSUE THREAD

**Issue by davinkevin** [axet/vget#23]
Hi,

When I use vget (very helpfull library by the way !!) to download video from youtube, sometimes I get some NullPointerException because in the method [YoutubeParser.extractEmbedded](https://github.com/axet/vget/blob/35ce619b4e9f35c5dc6be134dcf0d9d3f17c2e18/src/main/java/com/github/axet/vget/vhs/YouTubeParser.java#L245) the qs is empty, so the map.get("status") return a null pointer exception.

If you want to see how I use the library, you could find the source code in my personal [GitHub project](https://github.com/davinkevin/Podcast-Server/blob/39930e371fcb7249badceba3160492f8bb120b37/src/main/java/lan/dk/podcastserver/manager/worker/downloader/YoutubeDownloader.java#L109)

If you need some information, let me know.

Below, captures from the IDE when the problem occurs :
![capture d ecran 2014-08-09 a 01 30 56](https://cloud.githubusercontent.com/assets/1970922/3864183/4eff6560-1f55-11e4-95e3-996dba3a7f82.png)
![capture decran 2014-08-09 a 01 31 43](https://cloud.githubusercontent.com/assets/1970922/3864182/4ef9fb48-1f55-11e4-8e2b-65a94ba98f1b.png)

Thanks

**Comment by fadyro** [comment]
Hi, thank you for that great library, if am getting 301 redirection how can i proceed to retrieve the video?
