### ISSUE TITLE
Downloads above 720p

### ISSUE THREAD

**Issue by WickedGamingUK** [axet/vget#29]
At least from what I've tried, I cannot get any video downloads that are above 720p. I can successfully limit the video quality to anything below 720p, but I can't get it above it.

**Comment by burnaz** [comment]
<code>
        YoutubeInfo info = new YoutubeInfo(new URL(url));

        YouTubeParser parser = new YouTubeParser();

        List<VideoDownload> list = parser.extractLinks(info);

        for (VideoDownload d : list) {
            System.out.println(d.stream + " " + d.url);
        }
</code>

This list has only YoutubeInfo.StreamCombined, I want need to get YoutubeInfo.StreamSeparated to download 1080p videos, and audio separated.

The problem seems to be on <b>extractHtmlInfo</b> (YoutubeParser), code:

        // separate streams
        {
            Pattern urlencod = Pattern.compile("\"adaptive_fmts\": \"([^\"]*)\"");
            Matcher urlencodMatch = urlencod.matcher(html);
            if (urlencodMatch.find()) { // always false
                ...
            }
        }

**Comment by roulupen** [comment]
How to download a particular stream for YouTube on fly?

**Comment by davinkevin** [comment]
+1, interested by this enhancement if possible...

What could be the solution (even out of this project) to merge the stream ? ffmpeg / avconv ?

**Comment by axet** [comment]
'dev' now downloads two split streams 'audio' and 'video'

**Comment by davinkevin** [comment]
Do you have a roadmap for the release of the next version including this feature ?

**Comment by axet** [comment]
It will happens when someone fix download bug.

**Comment by davinkevin** [comment]
Thanks for the answer. 

I haven't seen the bug in the issue tracker... I will try to look at it and do a PR if I find something...
