### ISSUE TITLE
Extract SeparatedStream

### ISSUE THREAD

**Issue by burnaz** [axet/vget#34]
First of all, it's a great job, congratulations axet!

There is a way to extract <b>SeparatedStream</b>? I have tried, but it's not working, code doesn't find separated's pattern.

Thanks

**Comment by axet** [comment]
Please implement what are you talking about, and push it back here.

**Comment by burnaz** [comment]
@axet 
<code>

        YoutubeInfo info = new YoutubeInfo(new URL(url));

        YouTubeParser parser = new YouTubeParser();

        List<VideoDownload> list = parser.extractLinks(info);

        for (VideoDownload d : list) {
            System.out.println(d.stream + " " + d.url);
        }
</code>

This list has only YoutubeInfo.StreamCombined, I need to get YoutubeInfo.StreamSeparated to download 1080p videos, and audio separated.

The problem seems to be on <b>extractHtmlInfo</b> (YoutubeParser), code:

        // separate streams
        {
            Pattern urlencod = Pattern.compile("\"adaptive_fmts\": \"([^\"]*)\"");
            Matcher urlencodMatch = urlencod.matcher(html);
            if (urlencodMatch.find()) { // always false
                ...
            }
        }

I'm using version 1.1.23
