### ISSUE TITLE
Endless loop of retries

### ISSUE THREAD

**Issue by mikesena** [axet/vget#37]
Hi,

It looks like the code in `VGet::retry(VGetParser user, AtomicBoolean stop, Runnable notify, Throwable e)` won't actually exit after a defined number of attempts.

Experimenting with VGet, the code seemed to be running without exitting.  Turns out my proxy was down, but in running the sample again, it seems that it will just restart after 10 attempts.

I haven't done a change & made a pull request for this, as it seems like its by design to just re-try anyway?  I think that's odd though; shouldn't it fail after a defined number?

**Comment by axet** [comment]
It is by design.

User control the library by overriding this function or checking state using managed download.

Library have no idea about how many tries you want until fail. It may be done by passing "config" number but what for? You still need to write control retries code.
