### ISSUE TITLE
Discussion on Porting Code to ALv2.0

### ISSUE THREAD

**Issue by lewismc** [axet/vget#39]
Hi @axet, I am one of the lead developers of [Apache Nutch](http://nutch.apache.org); a well matured, heavily adopted production ready web crawler. We are EXTREMELY interested in implementing vget as a plugin so we can build the acquisition of video multimedia into our typical crawl cycles. 
Would you be interested in re-licensing your code under the [Apache Licence v2.0](http://www.apache.org/licenses/LICENSE-2.0) so that I could write the plugin implementation for Nutch, utilize your excellent project and release it with out next general release?
Thanks in advance for any questions and congratulations on vget, it is awesome.
Thanks, Lewis

**Comment by axet** [comment]
What is stopping you from using this library as a dependency?

**Comment by lewismc** [comment]
Hi @axet thank you for the reply
bq. What is stopping you from using this library as a dependency?
In short, license [incompatibilities](http://www.apache.org/licenses/GPL-compatibility.html) prevent us from using GNU licensed software (even as a dependency) and then packing it and distributing it within an official Apache software release.
It would be ideal if I were able to write this plugin knowing that I could package it and release it within the official Nutch distribution.
Thanks for any reply

**Comment by axet** [comment]
My friend. My project distributed under LGPLv3. It is compatible with your work.

**Comment by lewismc** [comment]
I've run into this issue many times when working to use, package and distribute third party licensed software under official Apache releases. I cannot release LGPLv3 code under an Apache software release. I will try my best to have a Nutch plugin and make it available but not as part of the release. Thanks for your time, I appreciate you taking the time to write.

**Comment by axet** [comment]
It is wrong to fight over a licence.

**Comment by lewismc** [comment]
I completely agree. As I provided in the link above though, I cannot ship LGPLv3 code with an Apache release which is a shame. There is no argument. I will implement the Nutch plugin as a community plugin and at least others can use it. It just means that we cannot hip it with the Nutch source code.

**Comment by axet** [comment]
If you see some compatibility issues with LGPL and Apache2 please discuss this instead of destroying GPL.
