### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by nlhkh** [axet/vget#40]
It keeps retrying and does not seem to have a limit on the number of retries.

I used both examples.

**Comment by stephenotalora** [comment]
well for one you need to use the AtomicBoolean that you should be passing to vGet.download/extract to tell the corresponding threads when to stop. 

Second of all I do agree with you there's something going on with the download method I have not not had a chance to look into and attempt to rectify. but vGet.extract does work and to my eyes that's the most important piece. I simply created my own download service in Java, is a bit low level as you will need to extract file bytes one at a time until you get EOF but that's exactly what I imagine vGet.download doing.

**Comment by nlhkh** [comment]
Could you share your code that works on downloading a youtube video?

**Comment by SushilGC** [comment]
hi,I have also tried which is not working.
@stephenotalora  Could you please share us some code and let us know when this issue is going to get fixed.

**Comment by stephenotalora** [comment]
I have this working... I've been caught up with work but I will add an example some time this week and will attempt to fork the repo to implement a permanent solution. just bare with me for a little longer folks I should have more time towards the end of this week.

**Comment by nlhkh** [comment]
Thanks @stephenotalora !

**Comment by SushilGC** [comment]
Great one and Thanks @stephenotalora

**Comment by JohnPucciarelli** [comment]
@stephenotalora any updates? appreciate any help

**Comment by sarnobat** [comment]
I have this issue too. I look forward to a fix. I depend on this library :)

**Comment by efulmo** [comment]
confirm! Does not work anymore! Here is suppressed stacktrace:

```
com.github.axet.wget.info.ex.DownloadIOCodeError
	at com.github.axet.wget.RetryWrap.check(RetryWrap.java:148)
	at com.github.axet.wget.info.URLInfo.extractNormal(URLInfo.java:204)
	at com.github.axet.wget.info.URLInfo$2.download(URLInfo.java:101)
	at com.github.axet.wget.info.URLInfo$2.download(URLInfo.java:1)
	at com.github.axet.wget.RetryWrap.run(RetryWrap.java:78)
	at com.github.axet.wget.RetryWrap.wrap(RetryWrap.java:112)
	at com.github.axet.wget.info.URLInfo.extract(URLInfo.java:88)
	at com.github.axet.wget.info.DownloadInfo.extract(DownloadInfo.java:271)
	at com.github.axet.vget.info.VGetParser.info(VGetParser.java:22)
	at com.github.axet.vget.VGet.retry(VGet.java:169)
	at com.github.axet.vget.VGet.extract(VGet.java:306)
	at com.github.axet.vget.AppManagedDownload.run(AppManagedDownload.java:103)
	at com.github.axet.vget.AppManagedDownload.main(AppManagedDownload.java:122)
	at com.github.axet.vget.YouTubeTest.main(YouTubeTest.java:6)
```

**Comment by nlhkh** [comment]
To those who are still looking to download video, there is a tool
YouTube-dl https://github.com/rg3/youtube-dl/. It is written in Python, and
is a command line utility, so you can invoke the command from within Java,
and stream the output to stdout, capture that output into a Java file. What
you need to install in addition to Java is Python and Ffmpeg. Not a fully
Java solution, but it works for me.

**Comment by efulmo** [comment]
Unfortunately, it is not my case. I need pure-Java solution because of environment restrictions.

**Comment by axet** [comment]
Guys. I wrote down explanation how vget works.

If you'd like to debug and find out why it stop working you can read the following:

https://github.com/axet/vget/blob/master/docs/YouTube.md

This opensource, I hope you will share your experience as as pull request.

**Comment by efulmo** [comment]
The problem is in "KoUT0ZfPiFk" video actually. Trying to get it using another endpoint I am getting message: "This video contains content from UMG, who has blocked it on copyright grounds". I tired to paste another video URL to YouTubeTest and it was downloaded successfully.

However YouTube-dl found some solution for it, because it is able to download even blocked videos like "KoUT0ZfPiFk". Will dig deeper into YouTube-dl implementation...
