### ISSUE TITLE
String index out of range: -1 for specific Youtube-vids

### ISSUE THREAD

**Issue by StigLau** [axet/vget#46]
Hi mr Vget 
I'm trying to download UtubeIds kRNmQmNSD90, vPHZlUcPx6s and related vids. 
Resulting in "StringIndexOutOfBoundsException: String index out of range: -1"
at ...vget.vhs.YouTubeParser$DecryptSignature.s(YouTubeParser.java:91) ....
Ignoring "-1" index', I get this type, for an example: EXTRACTING WEBM VP8(p360) VORBIS(k128)
I have tested out other, normal vids, where vget work as expected. The format here is maybe audio + still image, and this might just be a simple parsing issue.

**Comment by axet** [comment]
Depends on youtube video version/server (yes, here a few different) vget works or not. Some servers has encryption, some different url scheme.

You can investigate. Check this instruction [youtube](../tree/master/docs/YouTube.md)

**Comment by davinkevin** [comment]
Same for this video : https://www.youtube.com/watch?v=USm8i0DG1Sk

Will check the link you submit.

Thanks
