### ISSUE TITLE
Retrying all the Time

### ISSUE THREAD

**Issue by yazabara** [axet/vget#47]
https://github.com/axet/vget/issues/10 reproduced on 1.1.23

There is interest fact:
4un5x5gIQQ0 - works.
ykQQ7LhtUTM - not.

Thank you!

**Comment by axet** [comment]
Depends on youtube video version/server (yes, here a few different) vget works or not. Some servers has encryption, some different url scheme.

You can investigate. Check this instruction [YouTube.md](../tree/master/docs/YouTube.md)

**Comment by aaronwardle** [comment]
Hi 

I had a similar issue and it turned out if its running on SDK 23 or higher you now have to ask the user in the app for access to the storage. 

Aaron

**Comment by ankitgupta727** [comment]
How to stop retrying after 10
