### ISSUE TITLE
Download only webm

### ISSUE THREAD

**Issue by Litarvan** [axet/vget#51]
Hey, first thank you so much for your library.

I saw that vget download the mp4 AND the webm, actually I only want the audio so, ffmpeg can't convert the mp4 (drop an error, don't know why) but the webm works, but, the mp4 is very long to download and is useless, so is it possible to download only the .webm file ? I searched a lot and I didn't find sorry :/

Thanks you by advance

**Comment by axet** [comment]
It is youtube to decide what format available. If it has no webm then no...

**Comment by Litarvan** [comment]
Ok but, is it possible to detect if it has webm and then download only the webm ? Or if it hasn't, download the mp4 to convert it

**Comment by axet** [comment]
If you would check main page more carefully you will find following lines.

            // download maximum video quality from youtube
            // user = new YouTubeQParser(YoutubeQuality.p480);

            // download mp4 format only, fail if non exist
            // user = new YouTubeMPGParser();

**Comment by Litarvan** [comment]
Oh sorry didn't read this comment, but I already took the code of the main page and it isn't working with the current library version. I tried to adapt it but I couldn't. VideoInfo.getInfo() returns a list

**Comment by BloodShura** [comment]
I also need to download only the webm, but I actually found nothing which could provide me that.
`YouTubeMPGParser` will **not** download WEBMs, which is the opposite of what this issue is saying.
Also, I cannot create a new parser sub-class, and override `filter` method to not download MP4 containers, because this method is _package-protected_.

**Comment by Litarvan** [comment]
That's right, i modified the library for the package-protected method but's that's definetly a problem :/
