### ISSUE TITLE
fix(filename): same filename if extension is the same from youtube

### ISSUE THREAD

**Issue by davinkevin** [axet/vget#54]
Hi, 

I work on the integration of vget in my project, but I found something which seems to be a bug.

When I try to download video above 720p (like this one : https://www.youtube.com/watch?v=MjWdhGRGL5E), the video and the audio are both on mp4 format but in separate files.
The problem is when I try to download it, the system write all the data on the same file... 

![image](https://cloud.githubusercontent.com/assets/1970922/15630644/35de9b9a-2544-11e6-9c0a-9ec605ddc428.png)

I can't find a way to change the destination of each file (the targetFile field in VideoFile is overwritten by the system automatically when the download begins).

I don't know if a trick exists to solve this problem or if the lib needs to be fixed to avoid this problem.

Thanks for your help

**Comment by davinkevin** [comment]
PR with a solution I tested, which is working, I let you decide if it's the right / better solution.

**Comment by axet** [comment]
thanks.

**Comment by davinkevin** [comment]
Thanks for this solution, but I think this lead to a regression when we use Vget.setTarget(File file) method to manually define the name of files (I remove all specific character to simplify file system management...)

If I write this (extracted from `AppManagedDownload`) : 
```java
v.extract(user, stop, notify);
File target = new File(path, "foo.custom.name.psdownload");
v.setTarget(target);
System.out.println("Title: " + videoinfo.getTitle());
System.out.println("File: " + target);
```
The system acts like previously in this issue, using the same file for both download.

You could see this here : 
![image](https://cloud.githubusercontent.com/assets/1970922/15634079/7213403a-25bb-11e6-9dc6-f13fb24a4c8a.png)

So, I don't know if you prefer me opening another issue or if you prefer re-opening this one.

Thanks for your help @axet 😄

**Comment by axet** [comment]
@davinkevin Now is incorrect to use setTarget(file) for multiple files download.

If you wish to set individual file, set it manually after you call .extract() and use setTarget on individual VideoFileInfo or use setTargetDir()
