### ISSUE TITLE
IOException when trying to download

### ISSUE THREAD

**Issue by iSach** [axet/vget#56]
Tested on Mac OS 10.11 and Linux Debian 7.

Getting this error:
http://hastebin.com/bobawagogu.avrasm
when running this code:
http://hastebin.com/rujomitohu.avrasm

build.gradle:
http://hastebin.com/ziyotalovu.vbs

Thanks in advance,
Sacha Lewin.

**Comment by axet** [comment]
Does new File("videos") exits?

**Comment by iSach** [comment]
Yes, I made a sysout, it's not null and the folder exists.

**Comment by axet** [comment]
Try to use full path instead of relative.

**Comment by iSach** [comment]
Used
`File file = new File("videos").getAbsoluteFile();`

Which is /Java/SamaritanV2/tests/videos

And it still exists this error:
http://hastebin.com/iwawunitof.avrasm

**Comment by axet** [comment]
I'm pretty sure directory does not exists.

**Comment by iSach** [comment]
(folder is now music, because it had no sense for being videos, but videos was there i just switched the name).

Folder is verified and *does* exist.

```
File file = new File("music").getAbsoluteFile();
System.out.println(file.exists());
```

Returns true.

**Comment by axet** [comment]
Sorry, I can't help you. You need to investigate what is wrong with your code. Try to call new File("music").mkdirs();

**Comment by Litarvan** [comment]
I already had this, it was a permission problem

**Comment by iSach** [comment]
Sorry for being rude, was just nervy because I've been trying to resolve that for hours.
@Litarvan 's solution worked.
But another error happens now, with FileUtils.sizeOf apparently, which is a really weird issue.
Have you maybe seen it yet?

http://hastebin.com/jiyuzineka.avrasm

**Comment by Litarvan** [comment]
I think you have two version of the commons library, one is overriding the one required by wget. Fork wget to update it.
