### ISSUE TITLE
Android Studio - targetCompatibilty 1.7 Error

### ISSUE THREAD

**Issue by saimemre** [axet/vget#65]
Hello, i have a android application. 

import vget in my project;

Error:Error converting bytecode to dex:
Cause: Dex cannot parse version 52 byte code.
This is caused by library dependencies that have been compiled using Java 8 or above.
If you are using the 'java' gradle plugin in a library submodule add 
targetCompatibility = '1.7'
sourceCompatibility = '1.7'
to that submodule's build.gradle file.

**Comment by axet** [comment]
This have nothing to do with vget. Update Android Studio build sdk.

**Comment by leoforney** [comment]
I'm getting the same error with the build tools 25.0.1

**Comment by leoforney** [comment]
I am very disappointed that @axet didn't respond re-opening this issue. I fixed this issue by cloning the vget repo to local machine then ran `mvn package` and it compiled into a jar that I would use in android studio.
