### ISSUE TITLE
Some links not working

### ISSUE THREAD

**Issue by ionutcristea** [axet/vget#66]
Example: 
https://www.youtube.com/watch?v=kj8DQ_mT7B8
https://www.youtube.com/watch?v=YQHsXMglC9A

Throws "Unable to decrypt signature!" error and can't retrieve download links for the video id.

**Comment by deprilula28** [comment]
Try it using an USA VPN. The problem is encryption which you have to crack for your country.

**Comment by axet** [comment]
works on my machine.

**Comment by deprilula28** [comment]
Like previously said, it's dependent in the encryption in your country.

Em sáb, 10 de dez de 2016 19:45, Alexey Kuznetsov <notifications@github.com>
escreveu:
